instance_type = "t2.micro"
key_name      = "ssh-key-ec2" #change this to your key-pair name
# ami_id            = "ami-0f918f7e67a3323f0"
stage             = "prod"
shutdown_minutes  = 40
s3_bucket_name    = "techeazy-logs-unique123ss" # Change this!
aws_region        = "ap-south-1"
# repo_url          = "https://github.com/techeazy-consulting/techeazy-devops"
verifier_lifetime = 40
alert_email       = "akhilc0101@outlook.com"
